package br.com.acolhimento.domain;
// Generated 30/10/2018 15:29:30 by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chamada generated by hbm2java
 */
@Entity
@Table(name = "chamada", catalog = "acolhimento")
public class Chamada implements java.io.Serializable {

	private ChamadaId id;
	private Usuario usuario;
	private Boolean falta;

	public Chamada() {
	}

	public Chamada(ChamadaId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public Chamada(ChamadaId id, Usuario usuario, Boolean falta) {
		this.id = id;
		this.usuario = usuario;
		this.falta = falta;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idChamadaData", column = @Column(name = "idChamadaData", nullable = false, length = 10)),
			@AttributeOverride(name = "nprontuarioUsu", column = @Column(name = "nProntuarioUsu", nullable = false)) })
	public ChamadaId getId() {
		return this.id;
	}

	public void setId(ChamadaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nProntuarioUsu", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "falta")
	public Boolean getFalta() {
		return this.falta;
	}

	public void setFalta(Boolean falta) {
		this.falta = falta;
	}

}
