package br.com.acolhimento.domain;
// Generated 30/10/2018 15:29:30 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "acolhimento")
public class Empresa implements java.io.Serializable {

	private String cnpjEmp;
	private Endereco endereco;
	private String nomeEmp;
	private short numeroVagasEmp;
	private String razaoSocialEmp;

	public Empresa() {
	}

	public Empresa(String cnpjEmp, String nomeEmp, short numeroVagasEmp) {
		this.cnpjEmp = cnpjEmp;
		this.nomeEmp = nomeEmp;
		this.numeroVagasEmp = numeroVagasEmp;
	}

	public Empresa(String cnpjEmp, Endereco endereco, String nomeEmp, short numeroVagasEmp, String razaoSocialEmp) {
		this.cnpjEmp = cnpjEmp;
		this.endereco = endereco;
		this.nomeEmp = nomeEmp;
		this.numeroVagasEmp = numeroVagasEmp;
		this.razaoSocialEmp = razaoSocialEmp;
	}

	@Id

	@Column(name = "cnpjEmp", unique = true, nullable = false, length = 20)
	public String getCnpjEmp() {
		return this.cnpjEmp;
	}

	public void setCnpjEmp(String cnpjEmp) {
		this.cnpjEmp = cnpjEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEndereco")
	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	@Column(name = "nomeEmp", nullable = false, length = 20)
	public String getNomeEmp() {
		return this.nomeEmp;
	}

	public void setNomeEmp(String nomeEmp) {
		this.nomeEmp = nomeEmp;
	}

	@Column(name = "numeroVagasEmp", nullable = false)
	public short getNumeroVagasEmp() {
		return this.numeroVagasEmp;
	}

	public void setNumeroVagasEmp(short numeroVagasEmp) {
		this.numeroVagasEmp = numeroVagasEmp;
	}

	@Column(name = "razaoSocialEmp", length = 60)
	public String getRazaoSocialEmp() {
		return this.razaoSocialEmp;
	}

	public void setRazaoSocialEmp(String razaoSocialEmp) {
		this.razaoSocialEmp = razaoSocialEmp;
	}

}
