package br.com.acolhimento.domain;
// Generated 30/10/2018 15:29:30 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "acolhimento")
public class Log implements java.io.Serializable {

	private Integer idLog;
	private Funcionario funcionario;
	private Date dataLogin;
	private Date dataLogoff;
	private String tipoEntradaOuAlteracao;
	private String tipoRelatorioGerado;

	public Log() {
	}

	public Log(Funcionario funcionario, Date dataLogin, Date dataLogoff) {
		this.funcionario = funcionario;
		this.dataLogin = dataLogin;
		this.dataLogoff = dataLogoff;
	}

	public Log(Funcionario funcionario, Date dataLogin, Date dataLogoff, String tipoEntradaOuAlteracao,
			String tipoRelatorioGerado) {
		this.funcionario = funcionario;
		this.dataLogin = dataLogin;
		this.dataLogoff = dataLogoff;
		this.tipoEntradaOuAlteracao = tipoEntradaOuAlteracao;
		this.tipoRelatorioGerado = tipoRelatorioGerado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idLog", unique = true, nullable = false)
	public Integer getIdLog() {
		return this.idLog;
	}

	public void setIdLog(Integer idLog) {
		this.idLog = idLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cpfFunc", nullable = false)
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataLogin", nullable = false, length = 10)
	public Date getDataLogin() {
		return this.dataLogin;
	}

	public void setDataLogin(Date dataLogin) {
		this.dataLogin = dataLogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataLogoff", nullable = false, length = 10)
	public Date getDataLogoff() {
		return this.dataLogoff;
	}

	public void setDataLogoff(Date dataLogoff) {
		this.dataLogoff = dataLogoff;
	}

	@Column(name = "tipoEntradaOuAlteracao", length = 40)
	public String getTipoEntradaOuAlteracao() {
		return this.tipoEntradaOuAlteracao;
	}

	public void setTipoEntradaOuAlteracao(String tipoEntradaOuAlteracao) {
		this.tipoEntradaOuAlteracao = tipoEntradaOuAlteracao;
	}

	@Column(name = "tipoRelatorioGerado", length = 20)
	public String getTipoRelatorioGerado() {
		return this.tipoRelatorioGerado;
	}

	public void setTipoRelatorioGerado(String tipoRelatorioGerado) {
		this.tipoRelatorioGerado = tipoRelatorioGerado;
	}

}
